apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-{{ .Release.Name }}-web
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-{{ .Release.Name }}-web
    spec:
      containers:
      - name: container-app
        image: {{.Values.web.imageName }}:{{.Values.web.imageTag }}
        ports:
        - containerPort: 5000
        env:
        - name: MONGODB_DB
          value: "admin"
        - name: MONGODB_HOST
          value: {{ .Chart.Name }}-mongodb
        - name: MONGODB_PORT
          value: "27017"
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: {{ .Values.mongodb.password }}
        - name: MONGO_INITDB_ROOT_USERNAME
          value: {{ .Values.mongodb.user }}